language: java
script: 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./gradlew build jacocoTR uploadArchives; else ./gradlew build; fi'

sudo: false

jdk:
  - oraclejdk8

env:
  global:
    - secure: "DpU32xA/tmGpATjE2yCV9YPxVAu+t1kWnSEPEM9pbWvi6/LwozPGYHYicvzxg1g1bi8ej6/hjQnLyo0ENOYDMZgv6hlh4LkPPLVz5JSqF/i9AS6k+Qb5idwLIX+WTZmiRbHyy2E4hL1Z8zK832F6htQNo2Erh16ecLcXXK650nlhTILQfBpymroxqT+iNdM0DPMUr/zNWHsvmKGCtvLRIsGEPFXoADmhGISs3kFdneHN6kwF4h5sgz1fjGbzZX94miC0KXNsTMS4Osj9tJXSGXbyLqtTQ34f/4UpS6hjgqLw9gaUfl9Y85Ix9QNCrATrBTBrsk+XatfHfVG2NyIA8QWSB/dYGNvVrcPTmOpRW9XypBTB5L4VRPbueBg8viScF43QSr+m8cSeCWvxCzta23zLYkYE4Jwr9QaJt87l6gfoeT6ktxDSf+c4btX0h6FCXc9r8LuwN0ocTE4z8jJ0OV3aaRBZjVp98n1vy+Zq2ubAxQvfIwkHRvJEth7i+blGY7BkodqxpU01a1TSzwPSkh76KMgyRs5cHoQjmFlndzymIKvY4jKCuA55qAx/w+qnXExPGy6+AiJUTEZhKgrPg/0ogzgKFp4hEtWDslyerMbDnzYmZCLaOfR2jFSqL4uvJe20Fy521Wk91061CsPGtdSkBRyR70ZJtQnKqL/qrLI="
    - secure: "hqJg6L0ATC/RCkxB+wnMFCMk/B1vcOhRbLpFWZl1qCnbK5IrcgZRFJvYnNsuFtPULlPP8HbgYy3Ind7wX1MyLSGysqF0ZB6/4esmY9JAjajVtKLaj5nsOBeNaG5cUJ0KWfJD8zecEx1/Ad2+LfsYbLw5zyk9STlfHqFHD/wsHijwkjDOSQhbAaUD8i5fW33lSgNPx9WpOrCNEhSXJw+iBcvldnmne+yDjWDfmJY4xZ7I6kpuHWDtcjutsEK0GSwhrPrbytBeZZ4vaJcGn/uqZ4nM31TOv6Owhmb87hzAXDq1KtkxHLFQSUtddgg5nY1UGDZ1XBCU8kuq19RUP1WhVnUdOzSpj0S91uAC7OOpun3YRoVyLXpFPwPSoPJMg1MH2oT0Z8CUOH02GbTryTtSYsvixuJHg+CQwj9u5N1PxaiFQIsE59zoZdT+RFOdFXR9XBAPi9Ie7BogiS9X+JmsrVGMcpK3u/SWxx3OHtdTDhOETketbLh+bM+6pWL8J68a7T4PjidQQ9hEOLKCldi9as6t7e5ym252JsIVkaTG4KLTJzqrHaN4NwpGQcPcKgeLQhh1Ufyw+t+RPxu+vgtyR27A2Sm0Wi50+kLI4hjjyX6bQ7EukIWsAbbNeDqa47KXFpdRmjpe468vT/eRiCT1HGpNQWBrMbUUplHfxTdV/uI="

before_install:
  - openssl aes-256-cbc -pass pass:$SONATYPE_PASS -in deploy/secring.gpg.enc -out deploy/secring.gpg -d
  - openssl aes-256-cbc -pass pass:$SONATYPE_PASS -in deploy/pubring.gpg.enc -out deploy/pubring.gpg -d
  - mkdir -p ~/.gradle
  - openssl aes-256-cbc -pass pass:$SONATYPE_PASS -in deploy/gradle.properties.enc -out ~/.gradle/gradle.properties -d
  - pip install --user codecov

after_success:
  - codecov
